### PR TITLE
fix: Fix payload method to send datas in task

### LINKED ISSUE #248: Payload on HTTP Request target always empty
#### Environment details

  - OS: Windows 10 64 bit 
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `@google-cloud/tasks` version: v2Beta3

#### Steps to reproduce

  1. Download the samples from this repo
  2. Run createHttpTask.js with a real project ID and queue name and set a delay
  3. Go to Google Cloud Tasks console to view created task
  4. Note that the payload is always empty

Alternatively, use a real URL target and note that the request.body is always empty on the target request handler (I'm using Firebase cloud functions).

### PR DESCRIPTION
**Pull request by ftx**
Hello,

Just add a fix for passing value in body when you create a task on samples.
Actually, when you create a task, no body is transmitted to CloudTask.

You need to add a Content-type on Headers.
And, on your server, you need to decrypt them to ascii.

Fixes #248  🦕

### CODE REVIEW

**Comment by ftx** [comment]
@googlebot I signed it!

**Comment by ftx** [comment]
@googlebot I signed it!

**Comment by bcoe** [comment]
@ftx thanks for the patch, what was the behavior without setting the header out of curiosity? this seems like something we shouldn't put on the user.

**Comment by ftx** [comment]
Without this header, no value was sent to CloudTask.

I checked with a describe in cli.

**Comment by bcoe** [comment]
@ftx 👍 I've opened up an internal issue to dig into this, and am digging into this on our end (will definitely land this unless there's a quick fix).

**Comment by ahmed-sigmalux** [comment]
I'm encountering the same problem and can only pass a body if I add an application/octet-stream header.

**Comment by heygambo** [comment]
Hey, @bcoe have you given up on fixing this issue?

**Comment by summer-ji-eng** [comment]
@heygambo I will take a look.

**Comment by summer-ji-eng** [comment]
> @googlebot I signed it!

**Comment by summer-ji-eng** [comment]
> Without this header, no value was sent to CloudTask.
> 
> I checked with a describe in cli.

@ftx thanks for your PR and could you help me reproduce the issue?
I am trying to reproduce the issue  in two ways here but the payload is not empty on Google cloud task console. 
1. run samples-test
2. create nodejs project to call @google-cloud/task v2beta3 without sending a header
OS: Windows10 x64
node: 10.15.3 (also tried latest verison)
npm:6.4.1 (also tried latest version)
@google-cloud/tasks version: v2Beta3

```
const {v2beta3} = require('@google-cloud/tasks');
const client = new v2beta3.CloudTasksClient();

const parent = client.queuePath('YOUR_PROJECT_ID', 'us-central1', 'summer-queue')
const payload = 'hello, summer';
inSeconds = 2;
const task = {
  httpRequest: {
    httpMethod: 'POST',
    url: 'https://example.com/taskhandler',
  }
}

if (payload) {
    task.httpRequest.body = Buffer.from(payload).toString('base64');
}

  if (inSeconds) {
    task.scheduleTime = {
      seconds: inSeconds + Date.now() / 1000,
    };
  }

const request = {
  parent: parent,
  task: task
}

client.createTask(request).then( task => console.log(`Task ${task[0].name} created`)).catch( error => console.log(error))
```

**Comment by summer-ji-eng** [comment]
Hi @heygambo, I am trying to dig into this problem.  Any update on your side? Did you have same problem?

**Comment by heygambo** [comment]
> Hi @heygambo, I am trying to dig into this problem. Any update on your side? Did you have same problem?

Hey @summer-ji-eng, we've made it work by providing a `content-type` of `application/octet-stream`.

Like so: 
```
const task = {
  httpRequest: {
    httpMethod: httpMethod,
    url,
    headers: {
      'content-type': 'application/octet-stream',
    },
  },
}
```

**Comment by summer-ji-eng** [comment]
> > Hi @heygambo, I am trying to dig into this problem. Any update on your side? Did you have same problem?
> 
> Hey @summer-ji-eng, we've made it work by providing a `content-type` of `application/octet-stream`.
> 
> Like so:
> 
> ```
> const task = {
>   httpRequest: {
>     httpMethod: httpMethod,
>     url,
>     headers: {
>       'content-type': 'application/octet-stream',
>     },
>   },
> }
> ```
@heygambo Thanks for response and digging into the problem to fix it. On my side, I am trying to reproduce the bug and estimate with team to see if it necessary to checkin the code. The mission here is to make developer life easier.

I am trying to reproduce the issue in two ways here but the payload is not empty on Google cloud task console.

- run samples-test
- create nodejs project to call @google-cloud/task v2beta3 without sending a header
OS: Windows10 x64
node: 10.15.3 (also tried latest verison)
npm:6.4.1 (also tried latest version)
@google-cloud/tasks version: v2Beta3
 
Any suggestion to reproduce on my end? Thank you very much.

**Comment by summer-ji-eng** [comment]
Double check that the payload work as expected.

Screen Shot 2020-06-18 at 10 37 48 AM

I am kindly close it. But feel free to open an issue or @summer-ji-eng if you have any further question. Thanks.

**Pull request closed without merging**
